// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package provider

import (
	"github.com/gmidorii/api-design/wire/app"
	"github.com/gmidorii/api-design/wire/repository/db"
)

// Injectors from hello.go:

func InitHelloApp() (app.Hello, error) {
	user := db.NewUser()
	hello := app.NewHello(user)
	return hello, nil
}
